services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/workspaces/todo-app
    environment:
      # appコンテナからdbコンテナへの接続情報
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: devuser
      DATABASE_PASSWORD: devpass
      DATABASE_NAME: devdb
    depends_on:
      - db
    tty: true
    stdin_open: true

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: devdb
    ports:
      - "54320:5432" # ホストOSから54320ポートでアクセス可能にする
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
